### ISSUE TITLE
Fetch Inject breaks links to fonts inside CSS

### ISSUE THREAD

**Issue by maszynka** [jhabdas/fetch-inject#27]
When I try to load font-awesome.css (from any kind of CDN) I always end up with an error.

## With example from this README.md:
```
fetchInject([
  '//cdn.jsdelivr.net/fontawesome/4.7.0/css/font-awesome.min.css'
]);
```
I end with _404_, and the broken URL becomes:

> https://s.codepen.io/boomerang/fonts/fontawesome-webfont.woff2?v=4.7.0

Demo of broken example:
https://codepen.io/maszynka/pen/zdONWe

When fa.css is normally attached it works:
https://codepen.io/maszynka/pen/ayopXe

## Example that works comes from:
https://wordcamp.habd.as/ (anyway something is wrong with its certificate).
Copied to the same demo:
https://codepen.io/maszynka/pen/mMbRZW

Working URL is partially encoded:
`  https://fonts.googleapis.com/css?family=Libre+Franklin%3A300%2C300i%2C400%2C400i%2C600%2C600i%2C800%2C800i&subset=latin%2Clatin-ext`

While original (from google fonts) is:
`https://fonts.googleapis.com/css?family=Libre+Franklin:300,300i,400,400i,600,600i,800,800i&amp;subset=latin-ext`

What's the rule for this encoding? It's not full encodeURIcomponent (only this part: `:300,300i,400,400i,600,600i,800,800i` is) and I do not understand how to make such a URL.

**Comment by jhabdas** [comment]
Thanks for spending time to open this issue and providing this level of detail @maszynka. I will look at this soon. Re: URL encoding of commas, that should be insignificant. (But I will double-check for you.) Re: The cert on my subdomain I'm aware it has expired.

**Comment by jhabdas** [comment]
Reviewed the following Pen loading FA icons:
https://codepen.io/maszynka/pen/zdONWe

Observed 404 loading font files.

Inspected CSS source of FA icons, which contains the following relative URL embedded in source:

```
src:url('../fonts/fontawesome-webfont.eot?v=4.7.0')
```

Relative URLs attempts to load non-existent resources, e.g.

```
https://s.codepen.io/boomerang/fonts/fontawesome-webfont.woff2?v=4.7.0
```

Because WOFF file does not exist at above address request fails as expected. To resolve this behavior please ensure any relative paths included in your CSS call files which exist at the location specified.

**Special note:**

When called externally `../fonts/foo` resolves to a path on an external server. When inlined into a document the relative path becomes relative to the document root and, therefore, will request files which must also be available on the server where called.

**Aside:**

It's a good idea to host your own font files as it mitigates the need to rely on third-party services, improves offline support for apps and also helps prevent SPOF in the normal case of font loading (which, even for Google fonts, [can take upwards of 17 seconds](https://core.trac.wordpress.org/ticket/41071#comment:4) to load otherwise).
