### ISSUE TITLE
add an option to pass request options

### ISSUE THREAD

**Issue by pongstr** [jhabdas/fetch-inject#30]
It would be nice to have an option where we can supply [request options](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Supplying_request_options) to bypass CORS issue.

Is it possible to squeeze the request options [here](https://github.com/jhabdas/fetch-inject/blob/master/src/fetch-inject.js#L27)?

```javascript
window.fetch(input, { ..request options.. })
  .then(res => ... )
  .catch(err => ...)
```

**Comment by jhabdas** [comment]
Hi @pongstr thanks for the request! @cvara has created a fork and [added the ability](https://github.com/cvara/fetch-inject/commit/9ab3a1f4051ec60e1c18e29c8e0ea9448e56b9f8) to pass in an options param. Before updating the main lib I'd prefer to see a compelling and specific use case to drive the enhancement given extensibility can be had right now through some light source modification.

**Comment by pongstr** [comment]
@jhabdas Thanks for your work! The issue I ran with is that whenever I try load resources from, lets say for example Material Lite stylesheets+js, I get a `cors` error. 

I will definitely checkout the fork, thank you very much!

**Comment by jhabdas** [comment]
No problem. FWIW cors is a huge bitch and the solve for 9 out of 10 cors issues (I just made that up) is at the server.

**Comment by cvara** [comment]
In my case, to be able to async request the facebook sdk, I needed to set fetch [request mode](https://developer.mozilla.org/en-US/docs/Web/API/Request/mode) to no-cors, and thats why I needed the ability to pass extra params to fetch. no-cors means that the receiving end may not alter the headers or the actual content of the resonse. In fact you are not even allowed to read its contents, so you may be able to inject them into the dom manually, which this library [tries to do](https://github.com/jhabdas/fetch-inject/blob/master/src/fetch-inject.js#L28).

So, at least for the no-cors usage scenario, to make optional fetch params relevant, we would need to be able to get around opaque responses, i.e. by doing someting like the following, instead of directly parsing the contents (if this is even possible, I haven't tested it):

```javascript
const script = document.createElement('script');
script.async = true;
script.src = src;
script.addEventListener('load', () => {
  // script has loaded, do something (i.e. resolve)
});
```

**Comment by jhabdas** [comment]
Thanks for chiming in @cvara. Not sure if it'll help but I'll just lob this in here while you guys are working out some details around CORS and the lib: https://github.com/whatwg/fetch/search?q=no-cors&type=Issues&utf8=✓
